# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 11:45
from __future__ import unicode_literals

from django.utils import timezone
from datetime import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='creation_date',
            field=models.DateTimeField(default=datetime.now(), verbose_name='creation date'),
            preserve_default=False,
        ),
    ]
