# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='creation_date',
            field=models.DateTimeField(verbose_name='date of creation'),
        ),
    ]
