# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20160917_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='creation_date',
        ),
    ]
