# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 11:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_remove_board_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date of creation'),
        ),
    ]
